[package]
name = "aoc2019" #
version = "0.1.0" 
authors = ["Jeff McBride"]
edition = "2018"

[dependencies]
anyhow = "1.0"
env_logger = "0.7"
itertools = "0.8"
num = "0.1"
simple_logger = "1.3"
error-chain = "0.12"
log = "0.4"
structopt = "0.3"   
